before_script:
  - python --version
  - python -m venv venv
  - source venv/bin/activate

build-job:
  stage: build
  script:
    - echo build-job

test-job:
  stage: test
  script:
    - echo test-job

deploy-prod:
  stage: deploy
  script:
    - echo deploy-prod
