image: python:3.11.3-slim-bullseye

before_script:
  - python -m venv venv
  - source venv/bin/activate
  - pip install -r requirements.txt

build-job:
  stage: build
  script:
    - echo build-job

test-job:
  stage: test
  script:
    - echo test-job
    - py.test
    - flake8 bin
    - flake8 tests

deploy-prod:
  stage: deploy
  script:
    - echo deploy-prod
