test-job:
  stage: test
  environment: venv
  script:
    - py.test

deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
  environment: production
