image: python:3.11.3-slim-bullseye

before_script:
  - python -m venv venv
  - source venv/bin/activate
  - pip install -r requirements.txt

build-job:
  stage: build
  script:
    - echo build-job

test-job:
  stage: test
  script:
    - echo test-job
    - py.test
    - flake8 bin
    - flake8 tests

deploy-prod:
  stage: deploy
  only:
    - main
  image: alpine
  before_script:
    - apk add --no-cache openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - echo deploy-prod
